### ISSUE TITLE
python3 callbacks should use type 'bytes' instead of 'str' to manipulate data

### ISSUE THREAD

**Issue by beg0** [libfuse/python-fuse#13]
When using python-fuse with python3, the python callbacks such as `write` or `read`,  should manipulate objects of type `bytes` instead of `str`.

In python3, type `str` is really for text representation, not raw data. However the C wrapper send `str` objects to `write` function and expect `str` objects are return value for `read`. With such a limitation, not all kind of data can be write or read throw a python-fuse file system, only text data can be wrote/read.

For python2, API should still send data using type `str` as in python2  binary data can be represented with such a type.

Here is an example that does not work for me right now. I got error EINVAL "Invalid argument"

```bash
$ mkdir /tmp/fioc
$ ./example/fioc.py /tmp/fioc

# Working use case
$ echo hello > /tmp/fioc/fioc

# no working use case
$ echo $'\x80' > /tmp/fioc/fioc
```

I tested read and write functions, maybe some others functions has similar limitations.

**Comment by pchampin** [comment]
Even for text data, handling 'str' in Python 3 is a problem, because the size and offset parameters are supposed to be in bytes, not in characters.
So returning naively `content[offset:offset+size]` does not return the correct data.

Consider the string `txt = "éà"`, which in UTF-8 is encoded as 4-bytes `C3 A9 C3 A0`.
Reading with offset=0 and limit=2 should return the bytes `C3 A9`, which is the string `"é"`. Unfortunately `txt[0:2]` will return `"éà"`.

To get the correct result above, one should write `txt.encode('utf-8')[0:2].decode('utf-8')`. Not only is this cumbersome, but it does not even work in all situations: consider now offset=1 and limit 2, which should yield the bytes 'A9 C3'. This is not a valid UTF-8 string, so `txt.encode('utf-8')[1:3].decode('utf-8')` will actually raise an exception. Preventing this exception would require even more complex code.

So I agree with @beg0, read and write (and possibly other functions) should return/expect `bytes` instead of `str` in Python3.

**Comment by robertsdotpm** [comment]
My good sir, thank you. You've just saved me hours of time.
